import Link from 'next/link';

export default function PrivacyPolicy() {
  return (
    <main className="min-h-screen bg-[#050014] text-white font-sans selection:bg-fuchsia-500/50 pt-32 pb-24 px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="text-fuchsia-400 hover:text-cyan-400 transition-colors text-sm font-bold uppercase tracking-widest mb-12 inline-block">
          ← Back to Hub
        </Link>
        
        <h1 className="text-4xl md:text-5xl font-black font-outfit mb-8 tracking-tighter">Privacy Policy</h1>
        
        <div className="space-y-8 text-[#94a3b8] leading-relaxed font-light text-lg">
          <section>
            <h2 className="text-2xl font-bold font-outfit text-white mb-4">1. Data Architecture & Telemetry</h2>
            <p>
              At specAI Engineering Ltd., we construct immutable boundaries around your corporate data. We do not engage with third-party tracking conglomerates. Our telemetry infrastructure operates on a zero-trust model, ensuring any diagnostic logs generated by your interactions are instantly hashed and retained temporarily solely for architectural stabilization.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-outfit text-white mb-4">2. Artificial Intelligence Processing</h2>
            <p>
              Inputs provided through our Engagement terminal or client environments are strictly isolated. We do not utilize client proprietary datasets to fine-tune shared foundational LLM architectures without explicit cryptographic consent. Your vectorized datasets belong to your enterprise vector stores entirely.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-outfit text-white mb-4">3. Cookie Topology</h2>
            <p>
              Our frontends operate using stateless security layers where possible. We deploy strictly mandatory cryptographic session tokens (cookies) exclusively to maintain authentication states and DDOS protection via Edge networking logic.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-outfit text-white mb-4">4. Strategic Inquiries</h2>
            <p>
              For any directives regarding localized data removal or GDPR compliance architectures, transmit your payloads to our central operations vector.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
