import Link from 'next/link';

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-[#050014] text-white font-sans selection:bg-fuchsia-500/50 pt-32 pb-24 px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        <Link href="/" className="text-cyan-400 hover:text-fuchsia-400 transition-colors text-sm font-bold uppercase tracking-widest mb-12 inline-block">
          ← Back to Hub
        </Link>
        
        <h1 className="text-4xl md:text-5xl font-black font-outfit mb-8 tracking-tighter">Terms of Service</h1>
        
        <div className="space-y-8 text-[#94a3b8] leading-relaxed font-light text-lg">
          <section>
            <h2 className="text-2xl font-bold font-outfit text-white mb-4">1. Enterprise Engagements</h2>
            <p>
              By transmitting data endpoints to specAI via our Engagement Terminal, your firm is establishing intent for secure systems architecture. Any conceptual proofs or intellectual payloads generated by specAI prior to formal contract signing remain the proprietary architecture of specAI Engineering Ltd.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-outfit text-white mb-4">2. Autonomous Infrastructure Boundaries</h2>
            <p>
              We design powerful autonomous loops (RAG APIs, n8n swarms, trading bots). Clients assume explicit legal responsibility for the outputs and kinetic downstream impacts generated by LLM architectures integrated into their proprietary networks. We mandate human-in-the-loop overrides on all generative outputs carrying financial, physical, or legal consequences.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-outfit text-white mb-4">3. Security Auditing Disclosures</h2>
            <p>
              Our Decentralized Security division conducts rigorous pre-flight audits. However, compiling code is inherently subject to external environment variables beyond our theoretical matrices. SpecAI assumes no financial liability for post-deployment black swan exploits against EVM environments or smart contracts unless a sovereign insurance protocol was explicitly configured in writing.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold font-outfit text-white mb-4">4. Code Execution & Rights</h2>
            <p>
              All foundational structural codebases constructed by specAI are licensed to the enterprise client strictly following complete milestone payments. Open source repositories leveraged by us remain attributed to their sovereign creators under MIT/GPL architecture paradigms.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}
